export { default as SignupForm } from "./SignupForm";
export { default as UserTypeToggle } from "./UserTypeToggle";
export { default as PasswordField } from "./PasswordField";
export { default as SignupInput } from "./SignupInput";
export { default as SelectOccupation } from "./SignupProvider/fields/SelectOccupation";
export { default as PhotoUpload } from "./PhotoUpload";
//export { default as DescriptionField } from "./SignupProvider/fields/DescriptionField";
export { default as ProviderIllustration } from "./SignupProvider/ProviderIllustration";
export { default as CustomerIllustration } from "./SignupCustomer/CustomerIllustration";
