spring.application.name=GoLocal

# DB Config
spring.datasource.url=${DB_URL}${DB_NAME}${DB_CREATION}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect

#JWT Configuration
app.jwt.secret=${JWT_SECRET_KEY}
app.jwt.expiration=3600000
app.jwt.refresh-expiration=86400000

#Admin Register Secret Key
admin.secretKey.secret=AdminIsManav